services:
#    blog.example:
#        class: BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  entradas.ultimas_entradas:
    class: \BlogBundle\Model\UltimasEntradas
    arguments: ["@doctrine.orm.entity_manager"]