

BlogBundle\Entity\Viaje:
  type: entity
  table: viaje
  oneToMany:
    entradas:
      targetEntity: Entrada
      mappedBy: viaje
  id:
    id: 
      type: integer
      generator: {strategy: AUTO}
  fields:
   name:
     type: string
     length: 255
   destino:
     type: string
     length: 255